require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'vendor/bundle/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 35
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 20
  
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9
