require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "vendor/bundle/**/*"

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 42

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 35
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 30

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 11

RSpec/ExampleLength:
  Max: 10
