name: notify

on:
  pull_request:
    branches: [ main ]
    types: [ review_requested ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: send_message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: |
            O PR \#${{ github.event.number }} foi solicitado revisão
            Veja https://github.com/portal-solus/backend/pull/${{ github.event.number }}
