name: notify

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: send_message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Um novo PR foi aberto -- veja https://github.com/portal-solus/backend/pulls
